mysql_root_password: devpw
mailhog_install_ssmtp: no

web_user: vagrant

wordpress_sites:
  kcm.dev: # name of the project. should be the same in all enviroments
    site_hosts:
      - kcm.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:drala/trellis-kassel_code_meetup.git
    site_install: true
    site_title: Kassel Code Meetup Beispiel
    admin_user: admin
    admin_password: admin
    admin_email: admin@kcm.dev
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    system_cron: true
    env:
      wp_home: http://kcm.dev
      wp_siteurl: http://kcm.dev/wp
      wp_env: development
      db_name: test_dev_db
      db_user: test_dev_user
      db_password: test_dev_password

mail_smtp_server: localhost:1025
mail_admin: admin@kcm.dev
mail_hostname: kcm.dev
ssmtp_auth_method: ""
ssmtp_start_tls: 'no'
ssmtp_tls: 'no'

ferm_enabled: false

php_error_reporting: 'E_ALL'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_track_errors: 'On'
php_mysqlnd_collect_memory_statistics: 'On'
php_opcache_enable: 0

xdebug_install: false
php_xdebug_remote_enable: true
php_xdebug_remote_connect_back: true
php_xdebug_remote_host: localhost
php_xdebug_remote_port: 9000
php_xdebug_remote_log: /tmp/xdebug.log
php_xdebug_idekey: XDEBUG
php_max_nesting_level: 200
